/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:102349de-8c2f-432a-bc63-52dd4aa4e58d",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_K6goWsBpI",
    "aws_user_pools_web_client_id": "663vfj35pm5cdfmpacrtvppkjr",
    "oauth": {}
};


export default awsmobile;
